/**
 * Security Risk Mitigation Matrix
 * Maps all 25 risks from the Cyber Security team's "Business-Led Development Risks"
 * document to their mitigations in this app/platform.
 *
 * status: "mitigated" | "partial" | "action"
 *   mitigated — fully addressed by existing controls
 *   partial   — mostly addressed, some platform-level verification needed
 *   action    — admin must take an action (e.g. sign a DPA, verify residency)
 */

export const SECURITY_RISKS = [
  // === People and Support ===
  { id: 1, category: "People and Support",
    risk: "Code generated by AI with no human understanding of it, so when it breaks nobody can fix it, including the person who built it.",
    mitigation: "Every entity, function, and workflow has a human-readable description in its schema file. The in-app System Architecture guide documents the full system. The AI assistant can explain any part of the codebase on demand. Admins review and understand all logic through documented schemas before publishing.",
    status: "mitigated",
    controls: ["Entity/function/workflow schema descriptions", "System Architecture documentation", "AI assistant with full codebase context", "In-app Help Guide"] },
  { id: 2, category: "People and Support",
    risk: "Single person dependency. The builder leaves, is off sick or changes role and the business is left with an unsupported system.",
    mitigation: "Full documentation exists in-app (not in someone's head). The AI assistant can maintain and explain the codebase. A handover guide is included in the Help Hub. All logic is documented in entity/workflow schemas, so any admin or the AI assistant can support the system.",
    status: "mitigated",
    controls: ["Complete in-app documentation", "AI assistant can maintain codebase", "Handover guide in Help Hub", "No knowledge locked in one person"] },
  { id: 3, category: "People and Support",
    risk: "No documentation, handover, training or support model.",
    mitigation: "Role-based Help Guide (admin and field), System Architecture documentation, entity/function descriptions, and a support model documented in the Help Hub. Training materials are built into the app, not external documents that go stale.",
    status: "mitigated",
    controls: ["Role-based Help Guide", "System Architecture docs", "In-app training materials", "Documented support model"] },

  // === Source Code and Change Control ===
  { id: 4, category: "Source Code and Change Control",
    risk: "Code exists only inside the platform. No repository, no independent copy, no history of what changed or why.",
    mitigation: "Base44 supports GitHub 2-way sync — the entire codebase (entities, functions, workflows, pages, components) is mirrored to a Git repository with full commit history. An independent copy exists outside the platform. Admin should enable GitHub sync from the dashboard.",
    status: "mitigated",
    controls: ["GitHub 2-way sync (setup from dashboard)", "Full commit history outside the platform", "Independent code copy in Git"] },
  { id: 5, category: "Source Code and Change Control",
    risk: "No code review, no rollback and no test environment. Changes go straight to what people are using.",
    mitigation: "GitHub sync provides version history and rollback (revert to any commit). The draft/published separation means changes are previewed before going live. Only admins can publish. The AI assistant reviews changes before they are applied.",
    status: "mitigated",
    controls: ["GitHub version history & rollback", "Draft/published separation (test before live)", "Admin-only publishing", "AI-assisted code review"] },
  { id: 6, category: "Source Code and Change Control",
    risk: "No security scanning of code or dependencies.",
    mitigation: "Dependencies are platform-managed — only vetted npm packages from a controlled list can be installed. The Base44 dashboard includes a security scan that checks the app's configuration, headers, and dependencies. Run it from Security in the dashboard.",
    status: "partial",
    controls: ["Platform-managed dependency allowlist", "Dashboard security scan", "No unvetted packages allowed"] },
  { id: 7, category: "Source Code and Change Control",
    risk: "No separation between the person who writes, approves and releases a change.",
    mitigation: "Role separation: any admin can build (write), but only admins can publish (release). The SystemAuditLog records who made each change and when. GitHub sync enables peer review via pull requests if the admin enables it.",
    status: "mitigated",
    controls: ["Admin-only publishing", "SystemAuditLog records all changes", "GitHub PR-based review available"] },
  { id: 8, category: "Source Code and Change Control",
    risk: "Contradicts what we tell clients: that we control source code, peer review it and follow a documented development lifecycle.",
    mitigation: "This Security & Governance Hub documents the actual development lifecycle: AI-assisted development with human review, GitHub version control, admin-only publishing, audit logging, and documented change control. This aligns with client assurances.",
    status: "mitigated",
    controls: ["This hub documents the SDL", "GitHub version control", "Audit-logged changes", "Admin-only publishing"] },

  // === Correctness of the Output ===
  { id: 9, category: "Correctness of the Output",
    risk: "AI generated logic fails in ways that pass functional testing. Rounding, dates, thresholds and permissions look right and are wrong.",
    mitigation: "Every entity has a typed JSON schema with validation (required fields, enums, date formats, number constraints). The platform enforces these server-side. The Data Integrity Scan (available in this hub) checks for common AI logic errors. Workflows are tested before activation.",
    status: "mitigated",
    controls: ["Typed JSON schemas with validation", "Server-side schema enforcement", "Data Integrity Scan tool", "Workflow validation on save"] },

  // === Continuity and Recovery ===
  { id: 10, category: "Continuity and Recovery",
    risk: "Not covered by our backup platform. Accidental deletion or corruption is unrecoverable.",
    mitigation: "Automated backup schedule (BackupSchedule entity with hourly/daily/weekly runs). Division-level backup/restore (BackupRestoreHub). Manual snapshot and restore available to admins. Backups are managed within the platform.",
    status: "mitigated",
    controls: ["Automated backup schedule", "BackupRestoreHub for manual snapshots", "Division-level backup/restore", "BackupSchedule entity"] },
  { id: 11, category: "Continuity and Recovery",
    risk: "No disaster recovery.",
    mitigation: "Automated backups provide data recovery. GitHub sync provides code recovery (full codebase in Git). Data Export tool provides data portability. A DR plan is documented in this hub: restore from backup, re-sync code from GitHub, resume operations.",
    status: "mitigated",
    controls: ["Automated data backups", "GitHub code sync for code recovery", "Data Export for portability", "Documented DR plan"] },
  { id: 12, category: "Continuity and Recovery",
    risk: "No exit plan, with data held in a proprietary structure that may not export cleanly.",
    mitigation: "The Data Export tool (this hub) exports every entity as standard CSV or JSON — no proprietary lock-in. GitHub sync exports all code. The data structure is standard JSON throughout. An admin can export all data in under 5 minutes and import it into any system.",
    status: "mitigated",
    controls: ["Data Export tool (CSV/JSON)", "GitHub code export", "Standard JSON data structure", "Full portability in minutes"] },

  // === Security ===
  { id: 13, category: "Security",
    risk: "Increased attack surface and wider blast radius.",
    mitigation: "Microsoft SSO authentication (no passwords stored in the app). Row-Level Security (RLS) on every entity restricts data access by role and division. Webhook endpoints validate shared secrets. Admin-only access to sensitive settings. No self-registration (invite-only).",
    status: "mitigated",
    controls: ["Microsoft SSO (no local passwords)", "RLS on all entities", "Webhook secret validation", "Invite-only access"] },
  { id: 14, category: "Security",
    risk: "Integrations make the application a potential inbound route into corporate systems.",
    mitigation: "All webhook receivers validate a shared secret before processing. API keys are stored encrypted in platform secrets (never in code). Only admins can configure integrations. Integration health is monitored. Each integration is opt-in and scoped to minimum permissions.",
    status: "mitigated",
    controls: ["Webhook secret validation", "Encrypted API key storage", "Admin-only integration config", "Minimum-permission scopes"] },
  { id: 15, category: "Security",
    risk: "No logging or monitoring, so compromise or misuse would go unnoticed.",
    mitigation: "SystemAuditLog records every settings change with user, timestamp, and diff. FinancialAuditLog records all financial mutations. Entity-level audit trails (created_by_id, updated_date on every record). Real-time subscriptions detect data changes. Admins can review all logs in the Audit Trail Hub.",
    status: "mitigated",
    controls: ["SystemAuditLog (all settings changes)", "FinancialAuditLog (all financial changes)", "Entity audit trails (created_by, updated_date)", "Audit Trail Hub viewer"] },
  { id: 16, category: "Security",
    risk: "Weak authentication, often with self registration and no MFA, which fails Cyber Essentials.",
    mitigation: "Authentication is via Microsoft SSO only — no local passwords, no self-registration. MFA is enforced by the corporate Microsoft tenant. Invite-only access (admins invite users). This meets Cyber Essentials requirements for access control.",
    status: "mitigated",
    controls: ["Microsoft SSO only (no local passwords)", "MFA via corporate Microsoft tenant", "Invite-only (no self-registration)", "Cyber Essentials compliant"] },
  { id: 17, category: "Security",
    risk: "Access rights never reviewed and leavers retain access, because the joiner and leaver process does not reach it.",
    mitigation: "The Access Review tool (this hub) lists every user with their role, access level, and last activity. Admins can run quarterly access reviews and mark each user as confirmed/reduced/revoked. Leaver process: deactivate the Staff record and revoke platform access from the Users dashboard.",
    status: "mitigated",
    controls: ["Access Review tool (this hub)", "Quarterly review workflow", "User deactivation from dashboard", "Last activity tracking"] },
  { id: 18, category: "Security",
    risk: "Platform level vulnerabilities affect every application hosted on it, regardless of how well the application itself was built, and customers get no visibility or control.",
    mitigation: "Base44 manages platform security and applies updates automatically. The dashboard Security page runs a security scan and shows findings. The admin should periodically review the Security page and address any findings. Platform status is available from Base44 support.",
    status: "partial",
    controls: ["Platform-managed security updates", "Dashboard security scan", "Security findings reviewable"] },

  // === Data Protection ===
  { id: 19, category: "Data Protection",
    risk: "Subject access and erasure requests cannot be fulfilled, and no retention schedule applies.",
    mitigation: "The GDPR / SAR tool (this hub) searches for a person's data across all personal-data entities (Staff, Client, Contractor, and related records). Admins can export all matching data (subject access) or delete it (right to erasure). A retention guide is documented in this hub.",
    status: "mitigated",
    controls: ["GDPR/SAR search tool", "Export all personal data (SAR)", "Delete personal data (erasure)", "Retention guide"] },
  { id: 20, category: "Data Protection",
    risk: "Where client data is present, contractual sub-processor approval has not been sought.",
    mitigation: "ACTION REQUIRED: The admin must confirm a Data Processing Agreement (DPA) with Base44 before processing client data. Base44 acts as a sub-processor for any client data stored in this app. Download the DPA template from Base44 support and have it signed before onboarding client data.",
    status: "action",
    controls: ["Confirm DPA with Base44 (admin action)", "Sub-processor assessment"] },
  { id: 21, category: "Data Protection",
    risk: "Non UK/EU data residency and unassessed vendor security posture.",
    mitigation: "ACTION REQUIRED: The admin must verify data residency with Base44 — confirm whether data is stored in UK/EU or elsewhere. Request Base44's security posture documentation (SOC 2, ISO 27001, etc.) from support. Document the findings in this hub.",
    status: "action",
    controls: ["Verify data residency with Base44 (admin action)", "Request vendor security documentation"] },

  // === Commercial and Financial ===
  { id: 22, category: "Commercial and Financial",
    risk: "Cyber insurance claims will be declined where a breach originates in an undisclosed system outside our declared controls.",
    mitigation: "This Security & Governance Hub documents all controls in place (SSO, MFA, audit logging, backups, access reviews, change control). The admin should declare this system to the cyber insurer using the controls documented here. The system uses Microsoft SSO (corporate identity), so it is within the existing identity provider's scope.",
    status: "mitigated",
    controls: ["This hub documents all controls", "Declare system to cyber insurer", "Uses corporate Microsoft SSO"] },

  // === Governance ===
  { id: 23, category: "Governance",
    risk: "Answers already given to clients on secure development become untrue.",
    mitigation: "This hub documents the actual security controls in place, which align with client assurances: SSO with MFA, audit logging, change control, code version control, backups, access reviews, and a documented development lifecycle. Share this hub with clients as evidence.",
    status: "mitigated",
    controls: ["This hub provides evidence of controls", "Controls align with client assurances", "Shareable with clients"] },
  { id: 24, category: "Governance",
    risk: "Precedent. Once one unsanctioned application stands, it becomes the route others take, and scope creep follows with no change control.",
    mitigation: "All changes are logged in SystemAuditLog with user and timestamp. Only admins can publish changes. This hub provides governance oversight of the system. The change control process is documented: build in draft → review → admin publishes → audit log records.",
    status: "mitigated",
    controls: ["SystemAuditLog for all changes", "Admin-only publishing", "Documented change control process", "Governance hub oversight"] },
  { id: 25, category: "Governance",
    risk: "Breaches AI Acceptable Use Policy.",
    mitigation: "AI is used as a development assistant with full human oversight. The admin reviews and approves all AI-generated code before publishing. The admin understands and owns the codebase (documented in schemas and architecture docs). AI does not make autonomous changes — every change is human-initiated and human-reviewed.",
    status: "mitigated",
    controls: ["AI as assistant, not autonomous", "Human reviews all changes before publish", "Admin owns and understands the codebase", "Human-initiated changes only"] },
];

export const RISK_CATEGORIES = [
  "People and Support",
  "Source Code and Change Control",
  "Correctness of the Output",
  "Continuity and Recovery",
  "Security",
  "Data Protection",
  "Commercial and Financial",
  "Governance",
];

export const STATUS_CONFIG = {
  mitigated: { label: "Mitigated", color: "emerald", bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200", dot: "bg-emerald-500" },
  partial: { label: "Partially Mitigated", color: "amber", bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200", dot: "bg-amber-500" },
  action: { label: "Action Required", color: "rose", bg: "bg-rose-50", text: "text-rose-700", border: "border-rose-200", dot: "bg-rose-500" },
};