/**
 * Power Apps Feature Compatibility Audit — single source of truth.
 *
 * Consumed by FeatureAuditTable (shared component) and embedded in both the
 * PowerApps Migration Roadmap and Azure Migration Plan PDF exports.
 *
 * Verdict legend:
 *   yes     → green tick  — fully transferable to Power Apps native
 *   partial → amber dot   — transferable with a workaround / native-equivalent
 *   no      → red cross   — cannot be done in pure Power Apps (needs external dep)
 *
 * target: the Power Platform component that replaces the feature
 *   Model-Driven App | Canvas App | Power Automate | Power BI | Power Pages |
 *   Dataverse | AI Builder | Custom Connector (Azure Function)
 */

export const FEATURE_AUDIT = [
  {
    module: 'Dashboard / Mission Control',
    icon: 'LayoutGrid',
    summary: 'Custom React widgets replaced by Power BI embedded dashboards — native equivalent, less interactive.',
    verdict: 'partial',
    features: [
      { name: 'Bento dashboard widget grid', verdict: 'partial', reason: 'Custom React widget grid with drag-resize cannot be replicated; Power BI dashboards are read-only tiles, not interactive widgets.', target: 'Power BI embedded', approach: 'Rebuild each widget as a Power BI visual embedded in the model-driven app dashboard area.' },
      { name: 'Live KPI stat tiles', verdict: 'yes', reason: 'KPI cards are standard Power BI visuals over Dataverse.', target: 'Power BI', approach: 'Build KPI cards in Power BI connected to Dataverse via DirectQuery.' },
      { name: 'Rig performance leaderboard', verdict: 'yes', reason: 'Standard leaderboard visual in Power BI.', target: 'Power BI', approach: 'Build a ranked table visual with metres, earnings, utilisation per rig.' },
      { name: 'Real-time data refresh (entity subscriptions)', verdict: 'no', reason: 'Power BI DirectQuery has a minimum 15-minute refresh; no push-based real-time updates like Base44 entity subscriptions.', target: 'Power BI (DirectQuery)', approach: 'Accept near-real-time (15-min refresh). For truly live data, use Power BI streaming datasets.' },
      { name: 'Customisable widget layout per user', verdict: 'no', reason: 'Power BI dashboard layouts are designer-controlled, not end-user customisable.', target: 'Power BI', approach: 'Provide multiple pre-built dashboards per role instead of per-user customisation.' },
      { name: 'Job Kanban board', verdict: 'partial', reason: 'No native Kanban in model-driven apps; canvas app can build one with a gallery.', target: 'Canvas App', approach: 'Build a Kanban-style gallery in a canvas app with drag-to-reorder.' },
      { name: 'Command centre quick actions', verdict: 'yes', reason: 'Model-driven app ribbon buttons + Power Automate flows.', target: 'Model-Driven App', approach: 'Add ribbon buttons that trigger instant Power Automate flows.' },
      { name: 'AI daily briefing widget', verdict: 'yes', reason: 'AI Builder / Azure OpenAI connector can generate daily summaries.', target: 'AI Builder / Power Automate', approach: 'Scheduled flow calls AI Builder, writes summary to Dataverse, displayed in dashboard.' },
      { name: 'Weather overview widget', verdict: 'yes', reason: 'Met Office / OpenWeather connector available in Power Automate.', target: 'Power Automate + Power BI', approach: 'Scheduled flow pulls weather, stores in Dataverse, Power BI displays.' },
      { name: 'Predictive insights widget', verdict: 'yes', reason: 'AI Builder prediction models available.', target: 'AI Builder', approach: 'Train AI Builder prediction model on historical data, surface results in Power BI.' },
    ],
  },
  {
    module: 'Scheduling / Rota Builder',
    icon: 'Calendar',
    summary: 'Drag-and-drop rota grid is the hardest parity item — canvas app reorderable gallery is less smooth on touch.',
    verdict: 'partial',
    features: [
      { name: 'Weekly rota grid (drag-and-drop)', verdict: 'partial', reason: 'Canvas app reorderable galleries exist but are less smooth than @hello-pangea/dnd on touch.', target: 'Canvas App', approach: 'Use a "tap to select → tap target cell" pattern on mobile; drag gallery on desktop.' },
      { name: 'Crew-to-rig assignment', verdict: 'yes', reason: 'Standard Dataverse create/update from a canvas app gallery.', target: 'Canvas App + Dataverse', approach: 'Gallery bound to gc_rotaassignment, Patch() on assignment.' },
      { name: 'Crew pairings (Lead Driller + Second Man)', verdict: 'yes', reason: 'Atomic dual-record creation via Power Automate flow.', target: 'Power Automate', approach: 'Flow creates both RotaAssignment records in a single run.' },
      { name: 'Conflict detection', verdict: 'yes', reason: 'Power Automate flow can query Dataverse for double-bookings.', target: 'Power Automate', approach: 'Flow on RotaAssignment create/update checks for conflicts, stamps has_conflict.' },
      { name: 'Smart-fill (copy last week)', verdict: 'yes', reason: 'Power Automate flow copies assignments from previous week.', target: 'Power Automate', approach: 'Instant flow triggered by button, copies assignments with date offset.' },
      { name: 'Template week copy', verdict: 'yes', reason: 'Same flow pattern as smart-fill with a date range.', target: 'Power Automate', approach: 'Flow copies assignments forward N weeks.' },
      { name: 'Permanent crew recurring pattern', verdict: 'yes', reason: 'Scheduled Power Automate flow generates assignments from the pattern.', target: 'Power Automate (scheduled)', approach: 'Daily scheduled flow reads Job.permanent_crew, generates RotaAssignment rows.' },
      { name: 'Leave / absence overlay', verdict: 'yes', reason: 'Dataverse lookup to Absence table, displayed as coloured banner.', target: 'Canvas App + Dataverse', approach: 'Gallery overlays absence records on the rota cells.' },
      { name: 'Rota publish + email', verdict: 'yes', reason: 'Power Automate flow + Outlook connector.', target: 'Power Automate + Outlook', approach: 'Flow emails each staff member their schedule, sets RotaWeek status.' },
      { name: 'Rota PDF export', verdict: 'partial', reason: 'Word template connector can generate PDFs but less flexible than jsPDF.', target: 'Power Automate + Word template', approach: 'Word template in SharePoint, populated by flow, exported as PDF.' },
      { name: 'Real-time rota updates (push)', verdict: 'no', reason: 'No push-to-grid in Power Apps; must use refresh-on-open + push notifications.', target: 'Push notifications', approach: 'Send push notification on publish; canvas app refreshes rota on screen focus.' },
      { name: 'Compliance block on publish', verdict: 'yes', reason: 'Flow checks compliance before allowing publish.', target: 'Power Automate', approach: 'Flow validates compliance, blocks or allows with override flag.' },
      { name: 'Staff swap modal', verdict: 'yes', reason: 'Canvas app dialog + Dataverse update.', target: 'Canvas App', approach: 'Modal dialog swaps staff_id on two assignments.' },
      { name: 'Availability heatmap', verdict: 'partial', reason: 'No native heatmap visual in canvas apps; Power BI can render one.', target: 'Power BI', approach: 'Embed a Power BI heatmap report in the scheduling area.' },
    ],
  },
  {
    module: 'Jobs / Projects Hub',
    icon: 'Briefcase',
    summary: 'Fully transferable — model-driven app with forms, views, and sub-grids over Dataverse.',
    verdict: 'yes',
    features: [
      { name: 'Job list / filtered views', verdict: 'yes', reason: 'Standard model-driven app views.', target: 'Model-Driven App', approach: 'Create views: active, by status, by division, by client.' },
      { name: 'Job form (multi-discipline)', verdict: 'yes', reason: 'Model-driven form with child table for disciplines.', target: 'Model-Driven App', approach: 'gc_jobdiscipline child table as a sub-grid on the Job form.' },
      { name: 'Job detail tabs (Overview, Crew, Logistics, Boreholes, Financials, Documents)', verdict: 'yes', reason: 'Model-driven form sections + sub-grids.', target: 'Model-Driven App', approach: 'Form sections with sub-grids for each tab.' },
      { name: 'Job status lifecycle (Planning → In Progress → Decommissioning → Completed)', verdict: 'yes', reason: 'Business process flow.', target: 'Model-Driven App (BPF)', approach: 'Business process flow with stages and gate conditions.' },
      { name: 'Job dependencies (prerequisite projects)', verdict: 'yes', reason: 'N:N relationship + validation flow.', target: 'Dataverse + Power Automate', approach: 'N:N relationship, flow checks dependencies before status change.' },
      { name: 'Site geolocation (lat/lng + what3words)', verdict: 'yes', reason: 'Text fields + Bing Maps control in canvas app.', target: 'Dataverse + Canvas App', approach: 'Store lat/lng/what3words; Bing Maps control for display.' },
      { name: 'Per-project weather thresholds', verdict: 'yes', reason: 'Fields on Job table + weather check flow.', target: 'Dataverse + Power Automate', approach: 'Override fields read by the daily weather alert flow.' },
      { name: 'Job document manager', verdict: 'yes', reason: 'SharePoint document library integration via Dataverse.', target: 'Dataverse + SharePoint', approach: 'Enable SharePoint document management on the Job table.' },
      { name: 'Job comments / activity feed', verdict: 'yes', reason: 'Timeline (Posts) control in model-driven apps.', target: 'Model-Driven App', approach: 'Enable timeline wall on the Job form.' },
      { name: 'Job milestones', verdict: 'yes', reason: 'Child table + flow for milestone triggers.', target: 'Dataverse + Power Automate', approach: 'gc_jobmilestone child table, flow checks milestone triggers daily.' },
      { name: 'Decommissioning checklist', verdict: 'yes', reason: 'Fields on Job table + canvas app wizard.', target: 'Canvas App + Dataverse', approach: 'Multi-step canvas screen writes to decommissioning_checklist JSON field.' },
      { name: 'Client portal link / token', verdict: 'yes', reason: 'Power Pages site with token-based access.', target: 'Power Pages', approach: 'Power Pages site reads job by portal_token query param.' },
    ],
  },
  {
    module: 'Assets Hub',
    icon: 'Package',
    summary: 'Fully transferable — model-driven app with forms, views, and compliance tracking.',
    verdict: 'yes',
    features: [
      { name: 'Asset list / grid with filters', verdict: 'yes', reason: 'Standard model-driven app views.', target: 'Model-Driven App', approach: 'Views by type, status, division, compliance state.' },
      { name: 'Asset form (rig flag, compliance, weight)', verdict: 'yes', reason: 'Model-driven form with all fields.', target: 'Model-Driven App', approach: 'Form with rig flag, compliance status, weight/volume fields.' },
      { name: 'Rig detail drawer (certificates, linked equipment)', verdict: 'yes', reason: 'Form with sub-grids for linked assets and service records.', target: 'Model-Driven App', approach: 'Sub-grids for child_asset_ids and ServiceRecord.' },
      { name: 'Asset compliance status (LOLER/PUWER/PAT)', verdict: 'yes', reason: 'Calculated fields + scheduled compliance check flow.', target: 'Dataverse + Power Automate', approach: 'Daily flow checks expiry dates, updates compliance_status.' },
      { name: 'Asset Panda bidirectional sync', verdict: 'yes', reason: 'Power Automate scheduled flow + HTTP connector.', target: 'Power Automate (scheduled + HTTP)', approach: 'Scheduled flow pulls from Asset Panda API, pushes updates back.' },
      { name: 'Asset QR code generation', verdict: 'yes', reason: 'Power Automate can generate QR codes via barcode connector.', target: 'Power Automate', approach: 'Flow generates QR on create, stores QR image in Dataverse.' },
      { name: 'Depreciation schedule (3 methods)', verdict: 'yes', reason: 'Power Automate flow calculates depreciation.', target: 'Power Automate', approach: 'Scheduled flow recalculates book value per asset.' },
      { name: 'Asset utilisation tracking (operating hours)', verdict: 'yes', reason: 'Flow aggregates drilling-duration logs.', target: 'Power Automate', approach: 'Scheduled flow sums hours from InvestigationLog, updates operating_hours.' },
      { name: 'Maintenance status (date + usage-based)', verdict: 'yes', reason: 'Flow checks next_service_date and hours_since_last_service.', target: 'Power Automate', approach: 'Daily flow flags due_soon / overdue assets.' },
      { name: 'Asset photo gallery (Asset Panda images)', verdict: 'yes', reason: 'Image fields in Dataverse + flow to cache URLs.', target: 'Dataverse + Power Automate', approach: 'Flow fetches images from Asset Panda, stores URLs in Dataverse.' },
      { name: 'Bulk QR label printing', verdict: 'partial', reason: 'No native label printing; Word template can generate labels.', target: 'Power Automate + Word template', approach: 'Word template generates a sheet of QR labels for printing.' },
    ],
  },
  {
    module: 'Fleet Hub',
    icon: 'Truck',
    summary: 'Fully transferable — model-driven app with Geotab/Holman sync via Power Automate.',
    verdict: 'yes',
    features: [
      { name: 'Vehicle list / cards', verdict: 'yes', reason: 'Model-driven app views.', target: 'Model-Driven App', approach: 'Views by status, maintenance state, division.' },
      { name: 'Vehicle form (MOT, tax, insurance)', verdict: 'yes', reason: 'Standard model-driven form.', target: 'Model-Driven App', approach: 'Form with all vehicle fields + MOT history sub-grid.' },
      { name: 'Live fleet map (Geotab)', verdict: 'partial', reason: 'No native live map in model-driven apps; canvas app + Bing Maps can render pins.', target: 'Canvas App + Bing Maps', approach: 'Canvas app pulls vehicle locations from Geotab, renders on Bing Maps control.' },
      { name: 'Geotab fleet sync', verdict: 'yes', reason: 'Scheduled Power Automate flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Hourly flow pulls vehicle locations from Geotab API.' },
      { name: 'Holman fleet sync', verdict: 'yes', reason: 'Same pattern as Geotab.', target: 'Power Automate (scheduled)', approach: 'Scheduled flow pulls from Holman API.' },
      { name: 'MOT history timeline', verdict: 'yes', reason: 'Sub-grid on Vehicle form.', target: 'Model-Driven App', approach: 'gc_vehiclemothhistory sub-grid on Vehicle form.' },
      { name: 'Maintenance booking', verdict: 'yes', reason: 'Child table + calendar view.', target: 'Model-Driven App', approach: 'gc_vehiclemaintenancebooking sub-grid with calendar control.' },
      { name: 'Predictive maintenance alerts', verdict: 'yes', reason: 'AI Builder prediction model.', target: 'AI Builder', approach: 'Train model on maintenance history, flow flags vehicles likely to need service.' },
      { name: 'Mileage reconciliation', verdict: 'yes', reason: 'Flow compares Geotab mileage vs submitted mileage.', target: 'Power Automate', approach: 'Scheduled flow flags discrepancies.' },
      { name: 'Trip history / route playback', verdict: 'partial', reason: 'No native route playback; Power BI can show trip data but not animated playback.', target: 'Power BI', approach: 'Power BI report shows trip history as a table + static map.' },
      { name: 'Vehicle safety events (Geofence)', verdict: 'yes', reason: 'Flow processes Geotab safety events.', target: 'Power Automate', approach: 'Webhook flow receives Geotab safety events, stores in Dataverse.' },
    ],
  },
  {
    module: 'Compliance Hub',
    icon: 'ShieldCheck',
    summary: 'Fully transferable — model-driven app with Mitti webhook sync and training matrix.',
    verdict: 'yes',
    features: [
      { name: 'Compliance item tracking (expiring/expired)', verdict: 'yes', reason: 'Model-driven views + scheduled expiry check flow.', target: 'Model-Driven App + Power Automate', approach: 'Daily flow checks expiry dates, updates status, sends alerts.' },
      { name: 'Training matrix / skills matrix', verdict: 'yes', reason: 'Model-driven app + Power BI heatmap.', target: 'Model-Driven App + Power BI', approach: 'N:N Staff ↔ TrainingRequirement, Power BI heatmap shows gaps.' },
      { name: 'Mitti / SafetyCulture audit sync', verdict: 'yes', reason: 'Power Automate HTTP trigger webhook.', target: 'Power Automate (HTTP trigger)', approach: 'Webhook flow receives Mitti audits, stores as SafetyReport records.' },
      { name: 'Audit dashboard (template grid)', verdict: 'yes', reason: 'Model-driven views grouped by template.', target: 'Model-Driven App', approach: 'Views grouped by template_id with audit counts.' },
      { name: 'Toolbox talks manager', verdict: 'yes', reason: 'Model-driven app with attendee tracking.', target: 'Model-Driven App', approach: 'gc_toolboxtalk table with attendee_ids N:N relationship.' },
      { name: 'Incident reporting (RIDDOR)', verdict: 'yes', reason: 'Model-driven form + workflow.', target: 'Model-Driven App + Power Automate', approach: 'Form for incident details, flow flags RIDDOR-reportable incidents.' },
      { name: 'RAMS / method statement manager', verdict: 'yes', reason: 'Document management + version control.', target: 'Dataverse + SharePoint', approach: 'SharePoint document library with versioning, linked to Job.' },
      { name: 'Compliance calendar', verdict: 'yes', reason: 'Model-driven calendar view.', target: 'Model-Driven App', approach: 'Calendar control on ComplianceItem view.' },
      { name: 'Action items from audits', verdict: 'yes', reason: 'Child table + assignment flow.', target: 'Dataverse + Power Automate', approach: 'Action items stored as InboxItem records, routed to assignees.' },
      { name: 'Crew shift status (safety checks)', verdict: 'yes', reason: 'Flow checks if safety forms completed.', target: 'Power Automate', approach: 'Flow verifies Mitti check timestamps on RotaAssignment.' },
    ],
  },
  {
    module: 'Billing / Financials (AFP + CVR)',
    icon: 'Receipt',
    summary: 'Hardest parity proof — dual-side AFP table is complex but achievable in canvas app + Dataverse.',
    verdict: 'partial',
    features: [
      { name: 'AFP builder (dual-side claim/assessment table)', verdict: 'partial', reason: 'Complex editable grid in canvas app; achievable but significant build effort.', target: 'Canvas App + Dataverse', approach: 'Editable gallery with dual-side columns, Patch() on cell edit.' },
      { name: 'AFP sheet tabs (Measured Works, Variations, EWR)', verdict: 'yes', reason: 'Multiple galleries filtered by sheet_name.', target: 'Canvas App', approach: 'Tab control with filtered galleries per sheet.' },
      { name: 'Variation summary + per-ref breakdown', verdict: 'yes', reason: 'Parent-child gallery pattern.', target: 'Canvas App', approach: 'Summary gallery, expandable breakdown gallery per VO ref.' },
      { name: 'Rate-card matching engine', verdict: 'yes', reason: 'Power Automate flow with fuzzy match expressions.', target: 'Power Automate', approach: 'Flow on AFPLineItem create, fuzzy-matches item vs gc_ratecarditem.' },
      { name: 'Dispute workflow (state machine)', verdict: 'yes', reason: 'Choice column + flow transitions.', target: 'Dataverse + Power Automate', approach: 'dispute_status Choice column, flow manages state transitions + history.' },
      { name: 'Auto-populate from field data', verdict: 'yes', reason: 'Scheduled flow reads field records, creates line items.', target: 'Power Automate (scheduled)', approach: 'Daily flow reads approved logs/timesheets, creates AFPLineItem records.' },
      { name: 'CVR builder', verdict: 'yes', reason: 'Same canvas app pattern as AFP.', target: 'Canvas App + Dataverse', approach: 'gc_cvr + gc_cvrlineitem tables, same editable gallery pattern.' },
      { name: 'AFP → CVR push', verdict: 'yes', reason: 'Instant flow copies agreed line items to CVR.', target: 'Power Automate', approach: 'Flow triggered by button, copies agreed items to CVR.' },
      { name: 'Invoice generation', verdict: 'yes', reason: 'Power Automate + Word template.', target: 'Power Automate + Word template', approach: 'Flow creates Invoice record, generates PDF via Word template.' },
      { name: 'Aged debtors dashboard', verdict: 'yes', reason: 'Power BI report.', target: 'Power BI', approach: 'Power BI report on Invoice table with aging buckets.' },
      { name: 'AFP/CVR Excel export', verdict: 'yes', reason: 'Power Automate + Excel template.', target: 'Power Automate + Excel template', approach: 'Flow populates Excel template in SharePoint, exports.' },
      { name: 'Billing rules engine', verdict: 'yes', reason: 'gc_billingrule table + flow evaluation.', target: 'Dataverse + Power Automate', approach: 'Flow matches log type + description against rules, stamps charge.' },
      { name: 'Cash flow forecast', verdict: 'yes', reason: 'Power BI report on Invoice + AFP data.', target: 'Power BI', approach: 'Power BI report projects cash flow from agreed AFPs + outstanding invoices.' },
      { name: 'POA price lock', verdict: 'yes', reason: 'Dataverse field + flow validation.', target: 'Dataverse + Power Automate', approach: 'locked_price field, flow prevents edits when locked.' },
      { name: 'Monthly AFP auto-creation', verdict: 'yes', reason: 'Scheduled flow creates next AFP in chain.', target: 'Power Automate (scheduled)', approach: 'Monthly flow creates next AFP with period_start = previous end + 1.' },
    ],
  },
  {
    module: 'Field Crew Mobile App',
    icon: 'Smartphone',
    summary: 'Canvas app with native GPS, camera, signature, and offline sync — native equivalent for most features.',
    verdict: 'partial',
    features: [
      { name: 'My Schedule (today + weekly)', verdict: 'yes', reason: 'Canvas app gallery bound to RotaAssignment.', target: 'Canvas App', approach: 'Gallery filtered by staff_id = current user, grouped by date.' },
      { name: 'My Profile (avatar, phone, compliance wallet)', verdict: 'yes', reason: 'Canvas app screens with native camera.', target: 'Canvas App', approach: 'Profile screen with Camera control for avatar, flip-card for certificates.' },
      { name: 'Shift Wizard (Checks → Arrive → Briefing → Work → End)', verdict: 'yes', reason: 'Multi-screen canvas app with native sensors.', target: 'Canvas App', approach: 'Sequential screens with geolocation, Mitti links, signature capture.' },
      { name: 'GPS tracking (foreground)', verdict: 'yes', reason: 'Power Apps Geolocation sensor.', target: 'Canvas App (Geolocation)', approach: 'Timer writes Location.Latitude/Longitude to Dataverse while shift active.' },
      { name: 'GPS tracking (background)', verdict: 'no', reason: 'Power Apps Geolocation only works while app is in foreground. No background tracking.', target: 'Custom Connector (external)', approach: 'Keep the existing external GPS app webhook strategy (receivePhoneGps flow) for background tracking.' },
      { name: 'Barcode scanning', verdict: 'yes', reason: 'Native BarcodeScanner control.', target: 'Canvas App (BarcodeScanner)', approach: 'BarcodeScanner control scans QR/barcodes, resolves via flow.' },
      { name: 'Signature capture', verdict: 'yes', reason: 'Native PenInput control.', target: 'Canvas App (PenInput)', approach: 'PenInput control captures signature, saves as image.' },
      { name: 'Camera / photo capture', verdict: 'yes', reason: 'Native Camera control.', target: 'Canvas App (Camera)', approach: 'Camera control captures photos, uploads to Dataverse.' },
      { name: 'Offline sync', verdict: 'yes', reason: 'Power Apps Mobile offline profile.', target: 'Canvas App (offline)', approach: 'Configure offline profile for Staff, RotaAssignment, Job; local writes sync on reconnect.' },
      { name: 'Push notifications', verdict: 'yes', reason: 'Power Apps Notifications connector.', target: 'Power Automate + Notifications', approach: 'Flow sends push notification to staff device.' },
      { name: 'Deliveries (driver hub)', verdict: 'yes', reason: 'Canvas app with delivery legs + sign-off.', target: 'Canvas App', approach: 'Gallery of delivery legs, sign-off screen with signature + photo.' },
      { name: 'Crew comms (messaging + requests)', verdict: 'yes', reason: 'Canvas app + Dataverse + flow routing.', target: 'Canvas App + Power Automate', approach: 'StaffRequest table, flow routes to office, canvas app shows responses.' },
      { name: 'Home location learning', verdict: 'partial', reason: 'Geolocation works in foreground only; cannot learn overnight positions in background.', target: 'Canvas App (limited)', approach: 'Crew manually confirms home location; flow stores lat/lng after 3 confirmations.' },
      { name: 'Geofence arrival/departure detection', verdict: 'partial', reason: 'Foreground geolocation can detect arrival/departure while app is open; not in background.', target: 'Canvas App (foreground only)', approach: 'Flow checks distance from site geofence on each GPS fix while app is open.' },
      { name: 'Timesheet submission', verdict: 'yes', reason: 'Canvas app form + flow approval.', target: 'Canvas App + Power Automate', approach: 'Form captures hours, flow submits for manager approval.' },
      { name: 'Recurring duties (auto-generated tasks)', verdict: 'yes', reason: 'Scheduled flow generates tasks from templates.', target: 'Power Automate (scheduled)', approach: 'Daily flow reads RecurringDutyTemplate, creates StaffTask records.' },
    ],
  },
  {
    module: 'Staff / HR Hub',
    icon: 'Users',
    summary: 'Fully transferable — model-driven app with Bob HR sync and permission groups as security roles.',
    verdict: 'yes',
    features: [
      { name: 'Staff list / directory', verdict: 'yes', reason: 'Model-driven app views.', target: 'Model-Driven App', approach: 'Views by team, worker type, division, active status.' },
      { name: 'Staff form (worker type, crew pairing, contacts)', verdict: 'yes', reason: 'Model-driven form with sub-grids.', target: 'Model-Driven App', approach: 'Form with contacts sub-grid, crew_parent_id self-reference.' },
      { name: 'Permission groups → security roles', verdict: 'yes', reason: 'Dataverse security roles replace custom permission groups.', target: 'Dataverse security roles', approach: 'Create 4 security roles, assign per staff via Entra ID groups.' },
      { name: 'Training records / compliance', verdict: 'yes', reason: 'N:N Staff ↔ TrainingRequirement + expiry tracking.', target: 'Dataverse + Power Automate', approach: 'N:N relationship, daily flow checks expiry.' },
      { name: 'Bob HR sync (absences, personal data)', verdict: 'yes', reason: 'Scheduled Power Automate flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Scheduled flow pulls from Bob HR API, syncs absences.' },
      { name: 'Staff onboarding (first-login profile setup)', verdict: 'yes', reason: 'Canvas app screen gated on onboarding_complete = false.', target: 'Canvas App', approach: 'Onboarding screen with photo + phone, sets onboarding_complete = true.' },
      { name: 'Staff invite / welcome email', verdict: 'yes', reason: 'Power Automate + Outlook connector.', target: 'Power Automate + Outlook', approach: 'Flow sends branded welcome email on Staff create.' },
      { name: 'Performance KPIs / incentive scores', verdict: 'yes', reason: 'Flow calculates metrics, Power BI displays.', target: 'Power Automate + Power BI', approach: 'Weekly flow calculates incentive scores, Power BI dashboard shows trends.' },
      { name: 'Holiday pay accrual', verdict: 'yes', reason: 'Scheduled flow calculates accruals.', target: 'Power Automate (scheduled)', approach: 'Monthly flow calculates accrued holiday pay per staff.' },
      { name: 'Staff reviews / appraisals', verdict: 'yes', reason: 'Model-driven app with review records.', target: 'Model-Driven App', approach: 'gc_staffreview table linked to Staff.' },
      { name: 'Rewards / badges / leaderboard', verdict: 'yes', reason: 'Dataverse tables + canvas app display.', target: 'Canvas App + Dataverse', approach: 'gc_reward + gc_rewardredemption tables, canvas app shows catalogue.' },
      { name: 'Access approval workflow', verdict: 'yes', reason: 'Flow on user create routes to approvers.', target: 'Power Automate', approach: 'Flow on Entra ID sign-in, creates pending access request, notifies approvers.' },
    ],
  },
  {
    module: 'Logistics / Deliveries',
    icon: 'Truck',
    summary: 'Fully transferable — canvas app for drivers + model-driven app for office management.',
    verdict: 'yes',
    features: [
      { name: 'Delivery board (office view)', verdict: 'yes', reason: 'Model-driven app views.', target: 'Model-Driven App', approach: 'Views of DeliveryLog by status, date, driver.' },
      { name: 'Driver hub (today delivery legs)', verdict: 'yes', reason: 'Canvas app gallery.', target: 'Canvas App', approach: 'Gallery of delivery legs for current driver, sorted by route order.' },
      { name: 'Load manifest / pick lists', verdict: 'yes', reason: 'Power Automate + Word/Excel template.', target: 'Power Automate + Word template', approach: 'Flow generates pick list PDF from delivery items.' },
      { name: 'Route optimisation', verdict: 'partial', reason: 'Bing Maps connector replaces Google Maps Directions; slightly different routing.', target: 'Power Automate + Bing Maps', approach: 'Flow calls Bing Maps route API, optimises stop order.' },
      { name: 'Safe-to-drive panel', verdict: 'yes', reason: 'Flow checks driver hours + vehicle safety.', target: 'Power Automate', approach: 'Flow validates driver hours and vehicle checks before allowing departure.' },
      { name: 'Delivery sign-off (signature + photo + GPS)', verdict: 'yes', reason: 'Canvas app with native controls.', target: 'Canvas App', approach: 'Sign-off screen with PenInput, Camera, Geolocation.' },
      { name: 'Delivery chain builder (multi-leg)', verdict: 'yes', reason: 'Child table for delivery legs.', target: 'Dataverse', approach: 'gc_deliveryleg child table linked to DeliveryLog.' },
      { name: 'Goods in receipt', verdict: 'yes', reason: 'Model-driven app form.', target: 'Model-Driven App', approach: 'gc_goodsinreceipt table with item, qty, supplier fields.' },
      { name: 'Site collection scanner', verdict: 'yes', reason: 'Canvas app + BarcodeScanner.', target: 'Canvas App', approach: 'Scanner screen records returned assets, updates JobAssetAssignment.' },
      { name: 'Trailer picker', verdict: 'yes', reason: 'Lookup field to Vehicle (trailer).', target: 'Model-Driven App', approach: 'Lookup field on DeliveryLog to Vehicle table.' },
    ],
  },
  {
    module: 'Scanner / Asset Command',
    icon: 'ScanLine',
    summary: 'Fully transferable — canvas app with native barcode scanner and offline sync.',
    verdict: 'yes',
    features: [
      { name: 'QR/barcode scanning', verdict: 'yes', reason: 'Native BarcodeScanner control.', target: 'Canvas App (BarcodeScanner)', approach: 'BarcodeScanner control scans, resolves asset via flow.' },
      { name: 'Asset sign-out / sign-in', verdict: 'yes', reason: 'Canvas app + Dataverse create/update.', target: 'Canvas App + Dataverse', approach: 'Scan creates JobAssetAssignment, updates quantity_available.' },
      { name: 'Scan basket (multi-item)', verdict: 'yes', reason: 'Canvas app collection.', target: 'Canvas App', approach: 'Local collection accumulates scanned items, committed as batch.' },
      { name: 'Book to vehicle', verdict: 'yes', reason: 'Lookup field + canvas app dialog.', target: 'Canvas App', approach: 'Dialog assigns scanned items to a vehicle delivery.' },
      { name: 'Drive-away modal', verdict: 'yes', reason: 'Canvas app screen.', target: 'Canvas App', approach: 'Confirmation screen with vehicle + asset list.' },
      { name: 'PAT testing console', verdict: 'yes', reason: 'Canvas app form + Dataverse.', target: 'Canvas App + Dataverse', approach: 'Form captures PAT test results, updates compliance_status.' },
      { name: 'Report fault from scanner', verdict: 'yes', reason: 'Canvas app dialog creates record.', target: 'Canvas App + Dataverse', approach: 'Dialog creates a fault record linked to the scanned asset.' },
      { name: 'Consumable usage logging', verdict: 'yes', reason: 'Canvas app + Dataverse update.', target: 'Canvas App + Dataverse', approach: 'Scan logs consumable usage, decrements stock level.' },
      { name: 'Scrap log', verdict: 'yes', reason: 'Canvas app form.', target: 'Canvas App + Dataverse', approach: 'Form records scrap with reason, photo, asset reference.' },
      { name: 'Offline scan queue', verdict: 'yes', reason: 'Power Apps offline profile + local collection.', target: 'Canvas App (offline)', approach: 'Scans stored in local collection, synced to Dataverse on reconnect.' },
    ],
  },
  {
    module: 'Investigation / Borehole Data',
    icon: 'FlaskConical',
    summary: 'Mostly transferable — AGS parsing needs a custom connector; borehole visualisation needs Power BI.',
    verdict: 'partial',
    features: [
      { name: 'Borehole card grid (grouped by job)', verdict: 'yes', reason: 'Model-driven app views grouped by job.', target: 'Model-Driven App', approach: 'Views of InvestigationLog grouped by job_id.' },
      { name: 'Borehole drill-down (depth, strata, SPT, samples)', verdict: 'partial', reason: 'Custom SVG depth column cannot render in model-driven forms; Power BI can render it.', target: 'Power BI', approach: 'Embed a Power BI report with the borehole visualisation in the form.' },
      { name: 'AGS file import', verdict: 'no', reason: 'Complex multi-group AGS parsing is too hard in pure Power Automate expressions.', target: 'Custom Connector (Azure Function)', approach: 'Wrap the existing AGS parser as an Azure Function exposed via custom connector.' },
      { name: 'KeyLogBook webhook receiver', verdict: 'yes', reason: 'Power Automate HTTP trigger flow.', target: 'Power Automate (HTTP trigger)', approach: 'HTTP trigger flow validates token, parses payload, writes records.' },
      { name: 'Driller remarks AI professionalisation', verdict: 'yes', reason: 'AI Builder / Azure OpenAI connector.', target: 'AI Builder / Azure OpenAI', approach: 'Flow sends raw remarks to AI Builder, stores professionalised description.' },
      { name: 'Site log review queue', verdict: 'yes', reason: 'Model-driven view + approve/query actions.', target: 'Model-Driven App', approach: 'View filtered by manager_review_status = pending, ribbon buttons for approve/query.' },
      { name: 'Geotech QC dashboards', verdict: 'yes', reason: 'Power BI reports.', target: 'Power BI', approach: 'Power BI reports on borehole completion, SPT distribution, strata summary.' },
      { name: 'Auto-pricing from billing rules', verdict: 'yes', reason: 'Flow on InvestigationLog create.', target: 'Power Automate', approach: 'Flow matches log_type + description against BillingRule, stamps charge.' },
      { name: 'Auto-timesheet generation', verdict: 'yes', reason: 'Flow creates Timesheet from approved logs.', target: 'Power Automate', approach: 'Flow on log approval creates Timesheet with activity duration.' },
      { name: 'OpenGround export', verdict: 'yes', reason: 'Power Automate HTTP connector.', target: 'Power Automate (HTTP)', approach: 'Flow writes AGS-formatted data to OpenGround endpoint.' },
      { name: 'Borehole completion status', verdict: 'yes', reason: 'Calculated column + flow fallback.', target: 'Dataverse + Power Automate', approach: 'Calculated column with flow fallback for data coverage.' },
      { name: 'Sample chain-of-custody', verdict: 'yes', reason: 'Child table + model-driven views.', target: 'Model-Driven App', approach: 'gc_sample child table with chain-of-custody fields.' },
      { name: 'Monitoring well management', verdict: 'yes', reason: 'Model-driven app.', target: 'Model-Driven App', approach: 'gc_monitoringwell table with readings sub-grid.' },
      { name: 'Lab test results', verdict: 'yes', reason: 'Model-driven app + Power BI.', target: 'Model-Driven App + Power BI', approach: 'gc_labtestresult table, Power BI shows results distribution.' },
    ],
  },
  {
    module: 'Reports Hub',
    icon: 'BarChart3',
    summary: 'Fully transferable — Power BI replaces the custom React report builder.',
    verdict: 'yes',
    features: [
      { name: 'Custom report builder', verdict: 'partial', reason: 'No drag-and-drop report builder; replaced by parameterised Power BI paginated reports.', target: 'Power BI (paginated)', approach: 'Build a library of parameterised paginated reports the user runs from the hub.' },
      { name: 'Rig performance report', verdict: 'yes', reason: 'Power BI report.', target: 'Power BI', approach: 'Parameterised report by date range, rig, job.' },
      { name: 'Crew performance report', verdict: 'yes', reason: 'Power BI report.', target: 'Power BI', approach: 'Parameterised report by staff, date range.' },
      { name: 'Job report (PDF)', verdict: 'yes', reason: 'Power Automate + Word template.', target: 'Power Automate + Word template', approach: 'Flow populates Word template, exports as PDF.' },
      { name: 'Scheduled report emails', verdict: 'yes', reason: 'Power Automate scheduled flow + Power BI export.', target: 'Power Automate (scheduled)', approach: 'Scheduled flow exports Power BI report as PDF, emails to recipients.' },
      { name: 'Compliance checks report', verdict: 'yes', reason: 'Power BI report.', target: 'Power BI', approach: 'Report on compliance items by status, expiry, staff.' },
      { name: 'Availability report', verdict: 'yes', reason: 'Power BI report on rota + absence data.', target: 'Power BI', approach: 'Report showing staff availability by date.' },
      { name: 'Supplier spend report', verdict: 'yes', reason: 'Power BI report on Supplier + JobCostItem.', target: 'Power BI', approach: 'Report aggregating spend by supplier, job, date.' },
      { name: 'Remaining work projection', verdict: 'yes', reason: 'Flow calculates + Power BI displays.', target: 'Power Automate + Power BI', approach: 'Flow computes remaining work from AFP line items, Power BI displays.' },
      { name: 'Power BI dataset integration', verdict: 'yes', reason: 'Native Power BI integration.', target: 'Power BI', approach: 'DirectQuery to Dataverse, embedded in model-driven apps.' },
    ],
  },
  {
    module: 'Settings Hub',
    icon: 'Settings',
    summary: 'Fully transferable — model-driven app for all configuration tables.',
    verdict: 'yes',
    features: [
      { name: 'ConfigList dropdown manager', verdict: 'yes', reason: 'Dataverse global Option Sets + gc_configlist table.', target: 'Dataverse Option Sets', approach: 'Global Option Sets for enums, gc_configlist for non-enum lists.' },
      { name: 'Permission group editor', verdict: 'yes', reason: 'Dataverse security role editor.', target: 'Dataverse security roles', approach: 'Edit security role privileges per table.' },
      { name: 'Division manager', verdict: 'yes', reason: 'Model-driven app for gc_division.', target: 'Model-Driven App', approach: 'Form + views for division management.' },
      { name: 'Email alert template builder', verdict: 'yes', reason: 'gc_emailalertsetting table + model-driven form.', target: 'Model-Driven App', approach: 'Form for subject, template, accent_color, recipients.' },
      { name: 'KeyLogBook config', verdict: 'yes', reason: 'gc_keylogbookconfig table.', target: 'Model-Driven App', approach: 'Form for webhook secret, API token, enabled toggle.' },
      { name: 'Mitti config (routing, forms, templates)', verdict: 'yes', reason: 'gc_mitticonfig table.', target: 'Model-Driven App', approach: 'Form for webhook secret, routing rules, safety form URLs.' },
      { name: 'AppSetting manager (Concur, Bob HR, HMRC CIS)', verdict: 'yes', reason: 'gc_appsetting table.', target: 'Model-Driven App', approach: 'Form for integration credentials, GL code mappings, markup rules.' },
      { name: 'Business config (working hours, travel deduction)', verdict: 'yes', reason: 'gc_businessconfig table.', target: 'Model-Driven App', approach: 'Form for required on-site minutes, travel deductible, VAT rate.' },
      { name: 'Geofence settings', verdict: 'yes', reason: 'gc_appsetting with geofence config.', target: 'Model-Driven App', approach: 'Form for default radius, per-site overrides.' },
      { name: 'Weather threshold settings', verdict: 'yes', reason: 'gc_appsetting with weather thresholds.', target: 'Model-Driven App', approach: 'Form for temp/wind/rain/lightning thresholds.' },
      { name: 'Overtime rate manager', verdict: 'yes', reason: 'gc_overtimerate table.', target: 'Model-Driven App', approach: 'Form for rate tiers, thresholds.' },
      { name: 'Backup / restore manager', verdict: 'yes', reason: 'Power Automate scheduled flow + Azure Blob Storage.', target: 'Power Automate + Azure Blob', approach: 'Scheduled flow exports Dataverse data to Azure Blob Storage.' },
      { name: 'System audit log viewer', verdict: 'yes', reason: 'Dataverse auditing + plugin.', target: 'Dataverse auditing', approach: 'Enable auditing on all tables, plugin writes to gc_systemauditlog.' },
      { name: 'Access gate settings (pending/rejected)', verdict: 'yes', reason: 'Model-driven app for approval routing config.', target: 'Model-Driven App', approach: 'Form for approver staff IDs, contact instructions.' },
    ],
  },
  {
    module: 'Integrations (External Sync)',
    icon: 'Workflow',
    summary: 'All 200+ backend functions map to Power Automate flows — native equivalents for every sync.',
    verdict: 'yes',
    features: [
      { name: 'Geotab fleet + timesheet sync', verdict: 'yes', reason: 'Scheduled flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Hourly/daily flow pulls from Geotab API.' },
      { name: 'Asset Panda sync (bidirectional)', verdict: 'yes', reason: 'Scheduled flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Daily flow pulls inventory, pushes updates.' },
      { name: 'Holman fleet sync', verdict: 'yes', reason: 'Scheduled flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Daily flow pulls from Holman API.' },
      { name: 'Mitti / SafetyCulture webhook', verdict: 'yes', reason: 'HTTP trigger flow.', target: 'Power Automate (HTTP trigger)', approach: 'Webhook flow receives audits, stores records.' },
      { name: 'Bob HR sync (absences, staff)', verdict: 'yes', reason: 'Scheduled flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Daily flow syncs absences and staff data.' },
      { name: 'Concur expense sync', verdict: 'yes', reason: 'Scheduled flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Weekly flow pulls expenses from Concur API.' },
      { name: 'HMRC CIS verification', verdict: 'yes', reason: 'Power Automate flow + HTTP connector.', target: 'Power Automate (HTTP)', approach: 'Flow calls HMRC CIS API, stores verification result.' },
      { name: 'Stripe payments', verdict: 'yes', reason: 'HTTP trigger webhook flow.', target: 'Power Automate (HTTP trigger)', approach: 'Webhook flow receives Stripe events, updates Invoice.' },
      { name: 'WhatsApp notifications', verdict: 'yes', reason: 'Twilio WhatsApp connector.', target: 'Power Automate + Twilio', approach: 'Flow sends WhatsApp message via Twilio connector.' },
      { name: 'SharePoint document sync', verdict: 'yes', reason: 'Native Dataverse + SharePoint integration.', target: 'Dataverse + SharePoint', approach: 'Enable SharePoint document management on Job table.' },
      { name: 'Met Office weather sync', verdict: 'yes', reason: 'Scheduled flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Daily flow pulls forecast from Met Office API.' },
      { name: 'Power BI dataset sync', verdict: 'yes', reason: 'Native Power BI integration.', target: 'Power BI', approach: 'DirectQuery or scheduled refresh from Dataverse.' },
      { name: 'Zapier webhook', verdict: 'yes', reason: 'HTTP trigger flow.', target: 'Power Automate (HTTP trigger)', approach: 'Webhook flow receives Zapier events.' },
      { name: 'Accounting sync (Xero/Sage)', verdict: 'yes', reason: 'Scheduled flow + HTTP connector.', target: 'Power Automate (scheduled)', approach: 'Flow pushes invoices to accounting system API.' },
      { name: 'OpenGround sync', verdict: 'yes', reason: 'Flow + HTTP connector.', target: 'Power Automate (HTTP)', approach: 'Flow writes AGS data to OpenGround endpoint.' },
    ],
  },
  {
    module: 'Client Portal',
    icon: 'Globe',
    summary: 'Fully transferable — Power Pages site with Dataverse data and secure token access.',
    verdict: 'yes',
    features: [
      { name: 'Portal dashboard (job progress)', verdict: 'yes', reason: 'Power Pages site with Dataverse list.', target: 'Power Pages', approach: 'Power Pages page shows job progress from Dataverse.' },
      { name: 'Job progress timeline', verdict: 'yes', reason: 'Power Pages + Dataverse view.', target: 'Power Pages', approach: 'Timeline page reads JobMilestone records.' },
      { name: 'Document viewer (client-visible)', verdict: 'yes', reason: 'SharePoint document library + Power Pages.', target: 'Power Pages + SharePoint', approach: 'Power Pages page lists client-visible documents.' },
      { name: 'Client feedback / comments', verdict: 'yes', reason: 'Power Pages form + Dataverse.', target: 'Power Pages + Dataverse', approach: 'Form writes to JobComment with client_visible = true.' },
      { name: 'Portal branding (per client)', verdict: 'yes', reason: 'gc_portalbranding table + Power Pages theme.', target: 'Power Pages', approach: 'Power Pages reads branding config, applies theme.' },
      { name: 'Secure token access', verdict: 'yes', reason: 'Power Pages with anonymous access + URL token.', target: 'Power Pages', approach: 'Power Pages page reads job by portal_token, no login required.' },
      { name: 'Portal user invites', verdict: 'yes', reason: 'Power Automate flow sends invite email.', target: 'Power Automate + Outlook', approach: 'Flow sends portal link to client contact.' },
      { name: 'Client payment (Stripe)', verdict: 'yes', reason: 'Power Pages + Stripe checkout flow.', target: 'Power Pages + Power Automate', approach: 'Power Pages page triggers Stripe checkout flow.' },
    ],
  },
  {
    module: 'Enterprise / Multi-Division',
    icon: 'Building2',
    summary: 'Fully transferable — Dataverse security roles with division-scoped row filters.',
    verdict: 'yes',
    features: [
      { name: 'Enterprise dashboard (cross-division rollup)', verdict: 'yes', reason: 'Power BI dashboard with division RLS.', target: 'Power BI', approach: 'Power BI report with RLS so enterprise admins see all divisions.' },
      { name: 'Division selector / switcher', verdict: 'yes', reason: 'Model-driven app area switcher.', target: 'Model-Driven App', approach: 'Multiple app areas per division, or a division filter on views.' },
      { name: 'Division-scoped RLS', verdict: 'yes', reason: 'Dataverse security roles with row filters.', target: 'Dataverse security roles', approach: 'Security role filters records by division_id = user division OR null OR admin.' },
      { name: 'Business unit management', verdict: 'yes', reason: 'gc_division table + model-driven app.', target: 'Model-Driven App', approach: 'Form + views for division management.' },
      { name: 'Cross-division resource board', verdict: 'yes', reason: 'Model-driven app view across divisions.', target: 'Model-Driven App', approach: 'View showing all staff/resources with division column.' },
      { name: 'Enterprise admin (managed divisions)', verdict: 'yes', reason: 'Security role with multiple division access.', target: 'Dataverse security roles', approach: 'Security role grants read access to managed division IDs.' },
      { name: 'Division backup / restore', verdict: 'yes', reason: 'Power Automate flow + Azure Blob.', target: 'Power Automate + Azure Blob', approach: 'Flow exports division data to Blob, restore flow imports.' },
    ],
  },
  {
    module: 'Automation / Workflows',
    icon: 'Zap',
    summary: 'All 200+ Base44 backend functions and 80+ workflows map to Power Automate flows.',
    verdict: 'yes',
    features: [
      { name: 'Scheduled automations (daily/weekly/monthly)', verdict: 'yes', reason: 'Power Automate recurrence triggers.', target: 'Power Automate (recurrence)', approach: 'Recurrence trigger with the appropriate frequency.' },
      { name: 'Entity-triggered automations (on create/update/delete)', verdict: 'yes', reason: 'Dataverse triggers in Power Automate.', target: 'Power Automate (Dataverse trigger)', approach: 'Flow triggered by Dataverse record create/update/delete.' },
      { name: 'Webhook-triggered automations', verdict: 'yes', reason: 'HTTP trigger flows.', target: 'Power Automate (HTTP trigger)', approach: 'When an HTTP request is received trigger.' },
      { name: 'Multi-step branching (switch conditions)', verdict: 'yes', reason: 'Power Automate switch / condition actions.', target: 'Power Automate', approach: 'Switch action with multiple cases.' },
      { name: 'Durable waits (hours/days)', verdict: 'yes', reason: 'Power Automate delay / delay until actions.', target: 'Power Automate (delay)', approach: 'Delay until action with ISO-8601 timestamp.' },
      { name: 'Autopilot toast/banner system', verdict: 'yes', reason: 'AutopilotControl table + canvas app toast.', target: 'Dataverse + Canvas App', approach: 'Flow writes AutopilotControl record, canvas app shows toast.' },
      { name: 'Inbox approval routing', verdict: 'yes', reason: 'Power Automate approvals + Dataverse.', target: 'Power Automate (approvals)', approach: 'Approval action routes to approvers, stores result in InboxItem.' },
      { name: 'SLA escalation checks', verdict: 'yes', reason: 'Scheduled flow checks SLA breaches.', target: 'Power Automate (scheduled)', approach: 'Hourly flow checks inbox items for SLA breaches, escalates.' },
    ],
  },
  {
    module: 'AI Hubs / Agents',
    icon: 'Sparkles',
    summary: 'AI Builder and Azure OpenAI replace InvokeLLM — native equivalents for all AI features.',
    verdict: 'yes',
    features: [
      { name: 'Staff assistant (in-app chat)', verdict: 'yes', reason: 'AI Builder / Azure OpenAI connector + canvas app chat.', target: 'AI Builder + Canvas App', approach: 'Canvas app chat screen, flow calls AI Builder for responses.' },
      { name: 'Scheduling assistant', verdict: 'yes', reason: 'AI Builder suggests crew allocations.', target: 'AI Builder + Power Automate', approach: 'Flow calls AI Builder with rota context, returns suggestions.' },
      { name: 'Drilling intelligence chat', verdict: 'yes', reason: 'AI Builder with borehole data context.', target: 'AI Builder + Power Automate', approach: 'Flow calls AI Builder with investigation data, returns insights.' },
      { name: 'AI delay prediction', verdict: 'yes', reason: 'AI Builder prediction model.', target: 'AI Builder', approach: 'Train prediction model on historical delay data.' },
      { name: 'AI remarks professionalisation', verdict: 'yes', reason: 'AI Builder text processing.', target: 'AI Builder', approach: 'Flow sends raw remarks, AI Builder returns professionalised text.' },
      { name: 'AI certificate classification', verdict: 'yes', reason: 'AI Builder document processing.', target: 'AI Builder (document processing)', approach: 'AI Builder model classifies certificate type and expiry.' },
      { name: 'AI daily briefing', verdict: 'yes', reason: 'AI Builder + scheduled flow.', target: 'AI Builder + Power Automate', approach: 'Daily flow generates briefing from system data via AI Builder.' },
      { name: 'WhatsApp/Telegram agent channels', verdict: 'partial', reason: 'WhatsApp via Twilio connector; Telegram has a connector but agent integration is manual.', target: 'Power Automate + Twilio', approach: 'Flow receives WhatsApp messages, calls AI Builder, sends response.' },
    ],
  },
];

// Summary counts for the header
export const AUDIT_SUMMARY = {
  totalModules: FEATURE_AUDIT.length,
  totalFeatures: FEATURE_AUDIT.reduce((s, m) => s + m.features.length, 0),
  yes: FEATURE_AUDIT.reduce((s, m) => s + m.features.filter(f => f.verdict === 'yes').length, 0),
  partial: FEATURE_AUDIT.reduce((s, m) => s + m.features.filter(f => f.verdict === 'partial').length, 0),
  no: FEATURE_AUDIT.reduce((s, m) => s + m.features.filter(f => f.verdict === 'no').length, 0),
};