// Complete manifest of all 200+ backend functions, categorized by trigger type.
// Used by the Power Automate flow generator to produce the right trigger config.

export const SCHEDULED_FLOWS = [
  'checkComplianceExpiry', 'checkVehicleMaintenance', 'checkSiteWeatherAlerts',
  'checkBillingReadiness', 'checkOverdueInvoices', 'checkPredictiveMaintenance',
  'checkGeofencePresence', 'checkInventoryAlerts', 'checkJobBudgetAlerts',
  'checkMilestoneTriggers', 'checkRetentionStatus', 'checkSiteReadiness',
  'checkSubconMargin', 'checkAllJobsAssetCompliance', 'checkAssetCompliance',
  'checkBOQVariations', 'checkDriverSafety', 'checkFloodRisk', 'checkGeotechAlerts',
  'checkIdleVehicles', 'checkInvoiceDiscrepancies', 'checkMileageDiscrepancies',
  'runScheduledBackups', 'runTrainingCompliance', 'runWeatherRostering',
  'runPayrollAutopilot', 'runCashFlowForecast', 'runRigProfitabilityCheck',
  'runDelayPrediction', 'runClientWeeklyReport',
  'syncBankHolidays', 'syncMetOfficeWeather', 'syncGeotabFleet', 'syncHolmanFleet',
  'syncAssetPanda', 'syncAssetCompliance', 'syncBobAbsences', 'syncConcurExpenses',
  'syncAccounting', 'syncOpenGround', 'syncPowerBI', 'syncPermanentCrew',
  'syncStaffDivisionFromTeam', 'syncStaffUserRoles', 'syncVehicleOperator',
  'syncBillableItemToAFP', 'syncPortalFeedbackToJobStatus',
  'sendDailyReminders', 'sendDailyStandup', 'sendDailyTimesheetSummary',
  'sendWeeklyProgressReport', 'sendScheduledReports', 'generateWeeklyOpsDigest',
  'generateMonthlyStatements', 'autoBuildDailyTimesheets', 'autoGenerateTransferLegs',
  'autoCreateAFPFromMilestone', 'autoPopulateNewAFP', 'autoCreateBillingFromRemarks',
  'autoBillAssetOnSite', 'autoBookMaintenance', 'autoMatchVendorInvoice',
  'autoGenerateInvoice', 'backfillDivisionTags', 'backfillKlbDurations',
  'recalculateDepreciation', 'recalculateUsageMaintenance', 'recalculateCVR',
  'refreshAllDraftAFPs', 'reGeocodeAllJobs', 'detectAutoBreaks',
  'calculateHolidayAccruals', 'calculateShiftDifferentials', 'calculateWeeklyIncentives',
  'classifyTrainingCertificates', 'chaseOverdueInvoices',
];

export const INSTANT_FLOWS = [
  'approveDelayLog', 'approveKeyLogBookLogs', 'approvePortalDocument',
  'calculateCharge', 'calculateJobFinancials', 'cloneJob', 'commitAFPParse',
  'commitCVRParse', 'commitBasketSignOut', 'commitConsumableUsage', 'commitGoodsIn',
  'commitTrainingImport', 'completeDecommissioning', 'confirmHomeLocation',
  'confirmAssetPandaLink', 'confirmPandaScanLink', 'createDeliveryTimesheetEntry',
  'createStripeCheckout', 'deduplicateStaff', 'ensureMyStaffProfile',
  'exportAFPToExcel', 'exportCVRPack', 'exportCVRToExcel', 'exportPayroll',
  'generateDelayLogFromRemarks', 'generateJobAGSExport', 'generateJobPack',
  'generateJobReport', 'generateRotaPDF', 'geocodeJobAddress', 'getCrewEarnings',
  'getEnterpriseStats', 'getJobWeatherStatus', 'getMyStaffProfile', 'getPortalBranding',
  'getRigProfitability', 'getRouteComparison', 'getSettingsHubStats', 'getStaffICalFeed',
  'getUnlinkedUsers', 'getVehicleLocationHistory', 'getVehicleSafetyEvents',
  'getVehicleUtilisation', 'greenPathApproveTimesheet', 'importConcurReconciliation',
  'importEWRApplicationData', 'importInternalCostRates', 'importLegacyArchive',
  'importPlannerSpreadsheet', 'importPrehistoricSnapshot', 'incrementalImport',
  'lockPOAPrice', 'logBriefingAsTask', 'logDailyWeather', 'logSystemAudit',
  'manageEmailAlerts', 'mergeWeeklyTimesheet', 'migrateCrews', 'migrateJobDisciplines',
  'migrateJobTeamTypes', 'migrateToDivisions', 'notifyAbsenceRequest',
  'notifyJobStatusChange', 'notifyMaintenanceBooking', 'notifyNewJob',
  'notifyTimesheetSubmitted', 'notifyTrainingBooking', 'optimizeDailyRoute',
  'parseAFPUpload', 'parseCVRUpload', 'parseEWRAFPUpload', 'populateAFPFromFieldData',
  'predictMaintenance', 'processAssetReturn', 'processEWRRateCardUpload',
  'processMasterPriceListUpload', 'processOffHire', 'processRateCardUpload',
  'processSORUpload', 'processSiteCollection', 'processStaffUpload', 'publishRotaWeek',
  'purgeCompletedJobs', 'pushAFPToCVR', 'pushAbsenceToBob', 'pushAllToAssetPanda',
  'pushAssetPhotoToPanda', 'pushAssetUpdateToPanda', 'pushMilestoneToClient',
  'pushSignOutToPanda', 'recordFinancialAudit', 'recordStaffLocation', 'redeemReward',
  'redirectRigToJob', 'refreshScannedAsset', 'releaseRetention',
  'replaceShiftsWithLeave', 'repriceAFPFromRateCard', 'requestStaffTraining',
  'resetAssignmentBriefing', 'resetDatabase', 'resolveAssetByQR',
  'resolveConsumableByBarcode', 'resolveLogPricing', 'restoreDivision',
  'retryAssetReturnSync', 'seedDemoData', 'sendAssignmentNotification',
  'sendBrandedInvite', 'sendCrewWhatsApp', 'sendScheduleEmail', 'sendStaffInvite',
  'sendWelcomeEmail', 'splitMultiSiteJobs', 'stampBillingCharge',
  'stampRigOnSiteFromDelivery', 'startDecommissioning', 'submitAFPToClient',
  'submitDailyTimesheet', 'suggestCrewAllocation', 'syncKeyLogBook', 'syncMitti',
  'syncGeotabTimesheets', 'testAssetPandaConnection', 'updateAssetComplianceOnMaintenance',
  'updateMyAssignment', 'updateMyEmailPreference', 'updateMyOnboarding',
  'uploadProfilePhoto', 'validateCompaniesHouse', 'validateRigAssignments',
  'validateRigTooling', 'verifyCIS', 'csvBulkImport', 'batchProcessImport',
  'cleanupDuplicateAssignments', 'reclassifyGhostJobs', 'backupDivision',
  'activateBillingContract', 'addPortalComment', 'acknowledgeSchedule',
  'bookAssetToStaff', 'getConfigListUsage', 'getAssetPandaGroupFields',
  'getAssetPandaImages', 'getAssetPandaLinkReview', 'getAssetPandaObject',
  'getDivisionScopedData', 'getJobByPortalToken', 'boqImportExport',
];

export const WEBHOOK_FLOWS = [
  'importAGS', 'geotabWebhook', 'holmanWebhook', 'assetPandaWebhook',
  'bobWebhook', 'receiveMittiData', 'receivePhoneGps', 'whatsappWebhook',
  'stripeWebhook', 'zapierWebhook', 'accountingWebhook',
];

export const ALL_FLOWS = [...SCHEDULED_FLOWS, ...INSTANT_FLOWS, ...WEBHOOK_FLOWS];
export const FLOW_COUNT = ALL_FLOWS.length;