import { Briefcase, Users, ShieldCheck, HardHat, BarChart3 } from 'lucide-react';

export const COMPLIANCE_HELP_TOPICS = [
  { title: 'Audit Dashboard', summary: 'Full Mitti audit intelligence — scores, trends, templates, photos, action items.', body: 'The **Audit Dashboard** pulls every synced Mitti audit into a template-grouped grid with per-category pass-rate sparklines. Drill into a template to see the filtered audit list (with CSV/PDF export), then click any audit to open the **detail drawer** — full check items with inline photos, a photo gallery strip with lightbox zoom, GPS, signature, and editable action items. The **trend chart** breaks pass rates down by category (Vehicle / POWRA / Equipment). Use **Recurring Failures** to spot check questions that fail repeatedly, and **Action Items** to track all open corrective actions across every audit with assignee, due date, and status.' },
  { title: 'Audit Photos', summary: 'Photos from Mitti audits now render inline with a full-screen lightbox.', body: 'When you open an audit in the detail drawer, all photos from every check item are aggregated into a **photo gallery strip** at the top. Click any thumbnail to open a full-screen **lightbox** with zoom, arrow-key navigation, and swipe between photos. Photos also appear inline on their parent check item. The backend resolves Mitti media IDs to direct image URLs automatically.' },
  { title: 'Action Items', summary: 'Track all open corrective actions across every Mitti audit with assignee, due date, and status.', body: 'The **Action Items** sub-tab (within Audit Dashboard) aggregates every action item from every synced audit into a single list. Filter by assignee or status, search by keyword, and see **overdue alerts** in red. Change an action item\'s status (Open / In Progress / Closed) directly from the list. Within the audit detail drawer, you can also edit assignee, due date, and status inline on each action item and save changes back to the audit.' },
  { title: 'Create Incident from Audit', summary: 'One-click escalation from a failed audit item to a formal incident report.', body: 'In the audit detail drawer, any failed check item has a **"Create incident from this failure"** link. Click it to open a pre-filled incident form with the auditor, job, site, date, and the failed item description auto-populated. You can also escalate the whole audit using the **Create Incident** button in the header. The created incident appears in the Incidents tab timeline.' },
  { title: 'Missing Checks', summary: 'Live grid of who hasn\'t completed their Mitti safety checks — red/amber/green per crew member.', body: 'The **Missing Checks** view cross-references today\'s rota with the division\'s configured Mitti check types (vehicle, POWRA, equipment, general). Crew with zero checks done are sorted to the top in red. Click any crew member to see their specific check timestamps. Filter by date, job, or search by name. Configure which checks are required in **Settings → Compliance Check Config**.' },
  { title: 'Incidents', summary: 'Safety incidents and failed audits in a filterable chronological timeline with RIDDOR tracking.', body: 'The **Safety Timeline** merges in-app incident reports with Mitti-flagged audit failures, sorted chronologically. Each entry shows **type badges**, **severity colour-coding**, and **RIDDOR status** (Pending / Submitted). Filter by incident type, severity, and date range. Use **Report Incident** to log a new safety event. The **H&S Stats** tab shows RIDDOR reportable vs submitted counts with a direct **Submit to HSE** link for pending items.' },
  { title: 'Readiness', summary: 'Site readiness gate, compliance calendar with urgency colour-coding, and crew certification pulse.', body: 'The **Readiness Gate** checks every project for compliance before work starts. The **Calendar** shows upcoming expiries with **colour-coded urgency** — red for expired, amber for ≤7 days, light amber for ≤30 days. The **Crew Certification Pulse** shows compliance status across the workforce with a valid/expiring/expired breakdown bar.' },
  { title: 'Training & Environment', summary: 'Toolbox talks with attendance tracking and carbon footprint by fuel type.', body: '**Toolbox Talks** records safety briefings delivered on site with attendee tracking and a quick schedule form. **Environmental** tracks the carbon footprint across the fleet with a fuel-type breakdown chart and identifies the highest-emission vehicles.' },
];

export const COMPLIANCE_ONBOARDING = {
  title: 'Welcome to the Compliance Hub',
  description: 'Full Mitti audit intelligence, incidents, readiness and training — all in one place.',
  steps: ['Connect Mitti in Settings → Integrations', 'Sync audits to populate the dashboard', 'Review failed audits and action items', 'Log incidents and toolbox talks'],
};

export const COMPLIANCE_QUICK_LINKS = [
  { to: '/admin', label: 'Projects', icon: Briefcase, state: { section: 'jobs' } },
  { to: '/staff', label: 'Staff', icon: Users },
  { to: '/assets', label: 'Assets', icon: HardHat },
  { to: '/billing', label: 'Financials', icon: ShieldCheck },
  { to: '/fleet', label: 'Fleet', icon: BarChart3 },
];