import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { format } from 'date-fns';
import { Tablet, CheckCircle2, ChevronRight, Clock, Info, Briefcase, ChevronDown } from 'lucide-react';
import DailyTaskLog from '@/components/DailyTaskLog';

/**
 * WorkingStep — the "Tasks" step of the ShiftWizard.
 *
 * Smart detection: if AGS-imported investigation logs exist for this job +
 * today, the driller is using KeyLogBook. The manual task-entry form is
 * hidden and a "Review Your Day" panel is shown instead — the driller's
 * timesheet was auto-generated by the webhook and they review/submit it
 * at the end of their shift.
 *
 * If no AGS data exists for today, the standard DailyTaskLog form is shown
 * so the driller can log their tasks manually (the fallback).
 *
 * A job switcher bar at the top lets staff switch between today's jobs
 * without leaving the task logging view. The selected job is passed to
 * DailyTaskLog as lockedJobId so the job dropdown is hidden.
 */
function JobSwitcherBar({ currentJobId, jobs, onChange }) {
  const [open, setOpen] = useState(false);
  const currentJob = jobs.find(j => j.id === currentJobId);

  if (jobs.length <= 1) {
    return (
      <div className="px-5 py-3 bg-emerald-50 border-b border-emerald-100 flex items-center gap-2">
        <Briefcase className="w-4 h-4 text-emerald-600 flex-shrink-0" />
        <span className="text-sm font-semibold text-emerald-900 truncate">{currentJob?.name || 'No job'}</span>
      </div>
    );
  }

  return (
    <div className="px-5 py-3 bg-emerald-50 border-b border-emerald-100 relative">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between gap-2"
      >
        <div className="flex items-center gap-2 min-w-0">
          <Briefcase className="w-4 h-4 text-emerald-600 flex-shrink-0" />
          <span className="text-sm font-semibold text-emerald-900 truncate">
            Logging for: {currentJob?.name || 'Select job'}
          </span>
        </div>
        <div className="flex items-center gap-1 text-emerald-700 flex-shrink-0">
          <span className="text-xs font-medium">Switch</span>
          <ChevronDown className={`w-4 h-4 transition ${open ? 'rotate-180' : ''}`} />
        </div>
      </button>
      {open && (
        <div className="absolute left-5 right-5 top-full mt-1 bg-white rounded-xl shadow-lg border border-slate-200 z-10 overflow-hidden">
          {jobs.map(j => (
            <button
              key={j.id}
              onClick={() => { onChange(j.id); setOpen(false); }}
              className={`w-full flex items-center gap-2 px-3.5 py-2.5 text-left text-sm transition ${
                j.id === currentJobId ? 'bg-emerald-50 text-emerald-900 font-semibold' : 'text-slate-700 hover:bg-slate-50'
              }`}
            >
              <Briefcase className="w-3.5 h-3.5 text-slate-400 flex-shrink-0" />
              <span className="truncate">{j.name}</span>
              {j.id === currentJobId && <CheckCircle2 className="w-4 h-4 text-emerald-600 ml-auto flex-shrink-0" />}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function KeyLogBookReviewPanel({ job, hasAutoTimesheet, onGoToEndOfShift }) {
  const today = format(new Date(), 'yyyy-MM-dd');
  const { data: autoTimesheets = [] } = useQuery({
    queryKey: ['auto-timesheets-check', job?.id, today],
    queryFn: () => base44.entities.Timesheet.filter({ job_id: job?.id, date: today, status: 'draft' }),
    enabled: !!job?.id,
  });

  // Check if any of today's draft timesheets were auto-generated from KeyLogBook
  const klbDrafts = autoTimesheets.filter(t =>
    (t.notes || t.task_description || '').toLowerCase().includes('keylogbook')
  );

  return (
    <div className="px-5 py-5 space-y-4">
      {/* Info banner */}
      <div className="flex items-start gap-2.5 bg-indigo-50 border border-indigo-100 rounded-xl px-4 py-3.5">
        <Tablet className="w-5 h-5 text-indigo-600 flex-shrink-0 mt-0.5" />
        <div className="min-w-0">
          <p className="text-sm font-bold text-slate-900">Your borehole logs are in KeyLogBook</p>
          <p className="text-xs text-slate-600 mt-0.5 leading-relaxed">
            All drilling data is recorded by your lead driller in KeyLogBook and synced automatically.
            You don't need to log tasks manually — your timesheet has been generated for you.
          </p>
        </div>
      </div>

      {/* Auto-generated timesheet status */}
      {klbDrafts.length > 0 ? (
        <div className="flex items-start gap-3 p-4 bg-emerald-50 border border-emerald-200 rounded-xl">
          <CheckCircle2 className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
          <div className="min-w-0 flex-1">
            <p className="text-sm font-semibold text-emerald-900">
              Timesheet ready for review
            </p>
            <p className="text-xs text-emerald-700 mt-0.5">
              {klbDrafts.length} entr{klbDrafts.length === 1 ? 'y' : 'ies'} auto-generated from KeyLogBook.
              Review and submit your timesheet at the end of your shift.
            </p>
          </div>
        </div>
      ) : (
        <div className="flex items-start gap-3 p-4 bg-blue-50 border border-blue-100 rounded-xl">
          <Info className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
          <div className="min-w-0 flex-1">
            <p className="text-sm font-semibold text-slate-800">
              Waiting for KeyLogBook data
            </p>
            <p className="text-xs text-slate-600 mt-0.5">
              Your lead driller hasn't synced today's logs yet. Your timesheet will appear here
              automatically once the data arrives from KeyLogBook.
            </p>
          </div>
        </div>
      )}

      {/* CTA to end of shift */}
      <button
        onClick={onGoToEndOfShift}
        className="w-full flex items-center justify-center gap-2 px-4 py-3.5 bg-primary text-white rounded-xl hover:bg-primary/90 active:scale-95 transition text-sm font-bold touch-manipulation shadow-sm"
      >
        <Clock className="w-4 h-4" />
        Review &amp; Submit My Day
        <ChevronRight className="w-4 h-4" />
      </button>
    </div>
  );
}

export default function WorkingStep({ staffId, job, assignment, onGoToEndOfShift }) {
  const today = format(new Date(), 'yyyy-MM-dd');
  const [activeJobId, setActiveJobId] = useState(job?.id || '');

  // Fetch today's assignments so we can show a job switcher
  const { data: todayAssignments = [] } = useQuery({
    queryKey: ['staff-assignments-today', staffId],
    queryFn: () => base44.entities.RotaAssignment.filter({ staff_id: staffId, assigned_date: today }),
    enabled: !!staffId,
  });
  const { data: allJobs = [] } = useQuery({
    queryKey: ['jobs-for-working-step'],
    queryFn: () => base44.entities.Job.list(),
  });

  const todayJobIds = [...new Set(todayAssignments.map(a => a.job_id))];
  const todayJobs = allJobs.filter(j => todayJobIds.includes(j.id));
  const activeJob = allJobs.find(j => j.id === activeJobId) || job;

  // Check for AGS-imported investigation logs for this job + today
  const { data: invLogs = [], isLoading } = useQuery({
    queryKey: ['klb-ags-check', activeJobId, today],
    queryFn: () => base44.entities.InvestigationLog.filter({ job_id: activeJobId, source: 'ags_import' }),
    enabled: !!activeJobId,
  });

  const todaysAgsLogs = invLogs.filter(l => l.date === today);
  const usingKeyLogBook = todaysAgsLogs.length > 0;

  if (isLoading) {
    return (
      <div className="px-5 py-8 flex items-center justify-center">
        <div className="w-6 h-6 border-2 border-slate-200 border-t-[#2E5A1A] rounded-full animate-spin" />
      </div>
    );
  }

  if (usingKeyLogBook) {
    return (
      <>
        <JobSwitcherBar currentJobId={activeJobId} jobs={todayJobs} onChange={setActiveJobId} />
        <KeyLogBookReviewPanel job={activeJob} onGoToEndOfShift={onGoToEndOfShift} />
      </>
    );
  }

  return (
    <>
      <JobSwitcherBar currentJobId={activeJobId} jobs={todayJobs} onChange={setActiveJobId} />
      <div className="px-0 py-0">
        <DailyTaskLog staffId={staffId} hideSubmit lockedJobId={activeJobId} />
      </div>
    </>
  );
}