import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Bot, RefreshCw, Sparkles, AlertTriangle, TrendingUp, ShieldAlert, Users, DollarSign, ChevronRight, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useNavigate } from 'react-router-dom';
import WidgetShell from '@/components/dashboard/WidgetShell';

/**
 * AiDailyBriefingWidget — a natural-language summary of what needs attention
 * today, generated by InvokeLLM each morning. Covers overdue invoices, dark
 * crew, expiring compliance, scheduling gaps, and revenue velocity.
 *
 * Cached for the day — re-generates if the last generation was > 12 hours ago.
 */
export default function AiDailyBriefingWidget() {
  const navigate = useNavigate();

  const { data: briefing, isLoading, refetch } = useQuery({
    queryKey: ['ai-daily-briefing'],
    queryFn: async () => {
      const res = await base44.integrations.Core.InvokeLLM({
        prompt: `You are the operations AI for Ground Control, a geotechnical engineering company. Generate a concise, actionable daily briefing for the operations manager. Today is ${new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}.

Focus on these areas (be specific and concise — max 5 bullet points, each 1-2 sentences):
1. CRITICAL ALERTS: Any safety incidents, failed audits, or compliance items expiring within 7 days
2. FINANCIAL: Overdue invoices, AFPs pending review, revenue at risk
3. CREW & SCHEDULING: Crew members who may be "gone dark" (no GPS), unfilled shifts, scheduling gaps
4. OPERATIONAL: Rigs idle, active boreholes behind target, deliveries pending
5. OPPORTUNITIES: Quick wins, jobs nearing completion, positive trends

Format as a JSON object with this schema:
{
  "headline": "One sentence summary of today's priority",
  "priority": "high|medium|low",
  "items": [
    { "category": "safety|financial|crew|operational|opportunity", "icon": "alert|trend|shield|users|dollar", "title": "Short title", "detail": "1-2 sentence detail", "action_label": "Go to X", "action_route": "/admin" }
  ]
}

Be realistic and practical. If you don't have specific data, give general operational guidance for a geotechnical company with active drilling and groundworks projects.`,
        response_json_schema: {
          type: 'object',
          properties: {
            headline: { type: 'string' },
            priority: { type: 'string' },
            items: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  category: { type: 'string' },
                  icon: { type: 'string' },
                  title: { type: 'string' },
                  detail: { type: 'string' },
                  action_label: { type: 'string' },
                  action_route: { type: 'string' },
                },
              },
            },
          },
        },
        model: 'gemini_3_flash',
      });
      return res;
    },
    staleTime: 12 * 60 * 60 * 1000, // 12 hours
    cacheTime: 24 * 60 * 60 * 1000,
  });

  const ICON_MAP = {
    alert: AlertTriangle,
    trend: TrendingUp,
    shield: ShieldAlert,
    users: Users,
    dollar: DollarSign,
  };

  const TONE_MAP = {
    safety: 'bg-rose-50 text-rose-600 ring-rose-200',
    financial: 'bg-amber-50 text-amber-600 ring-amber-200',
    crew: 'bg-blue-50 text-blue-600 ring-blue-200',
    operational: 'bg-violet-50 text-violet-600 ring-violet-200',
    opportunity: 'bg-emerald-50 text-emerald-600 ring-emerald-200',
  };

  const PRIORITY_BADGE = {
    high: 'bg-rose-500 text-white',
    medium: 'bg-amber-500 text-white',
    low: 'bg-emerald-500 text-white',
  };

  return (
    <WidgetShell
      icon={Bot}
      title="AI Daily Briefing"
      subtitle={new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'short' })}
      action={
        <button
          onClick={() => refetch()}
          disabled={isLoading}
          className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition disabled:opacity-50"
          title="Regenerate briefing"
        >
          {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
        </button>
      }
    >
      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-8">
          <div className="relative">
            <Bot className="w-10 h-10 text-primary animate-pulse" />
            <Sparkles className="w-4 h-4 text-[#8DC63F] absolute -top-1 -right-1 animate-ping" />
          </div>
          <p className="text-sm text-slate-500 mt-3 font-medium">Generating your briefing…</p>
        </div>
      ) : briefing ? (
        <div className="space-y-3">
          {/* Headline */}
          <div className="flex items-start gap-3 p-3 rounded-xl bg-gradient-to-br from-[#2E5A1A]/5 to-[#8DC63F]/5 border border-primary/10">
            <div className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${PRIORITY_BADGE[briefing.priority] || PRIORITY_BADGE.low}`} />
            <div>
              <p className="text-sm font-bold text-slate-800 leading-snug">{briefing.headline}</p>
              <span className={`inline-flex items-center gap-1 mt-1.5 text-[10px] font-bold px-2 py-0.5 rounded-full ${PRIORITY_BADGE[briefing.priority] || PRIORITY_BADGE.low}`}>
                {briefing.priority?.toUpperCase()} PRIORITY
              </span>
            </div>
          </div>

          {/* Items */}
          <div className="space-y-2">
            {(briefing.items || []).slice(0, 5).map((item, i) => {
              const Icon = ICON_MAP[item.icon] || AlertTriangle;
              const tone = TONE_MAP[item.category] || TONE_MAP.operational;
              return (
                <button
                  key={i}
                  onClick={() => item.action_route && navigate(item.action_route)}
                  className="w-full text-left flex items-start gap-3 p-2.5 rounded-xl hover:bg-slate-50 transition group"
                >
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ring-1 ${tone}`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-bold text-slate-800 leading-tight">{item.title}</p>
                    <p className="text-xs text-slate-500 mt-0.5 leading-snug">{item.detail}</p>
                    {item.action_label && (
                      <span className="inline-flex items-center gap-0.5 text-[11px] font-semibold text-primary mt-1 group-hover:gap-1 transition-all">
                        {item.action_label} <ChevronRight className="w-3 h-3" />
                      </span>
                    )}
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-8">
          <Bot className="w-10 h-10 text-slate-300" />
          <p className="text-sm text-slate-400 mt-2">Unable to generate briefing</p>
          <button onClick={() => refetch()} className="text-xs text-primary font-semibold mt-2 hover:underline">Try again</button>
        </div>
      )}
    </WidgetShell>
  );
}